from game.pieces.piece import Piece
from game.pieces.pawn import Pawn
from game.pieces.knight import Knight
from game.pieces.rook import Rook
from game.pieces.bishop import Bishop
from game.pieces.queen import Queen
from game.pieces.line import Line
from game.pieces.diagonal import Diagonal
from game.pieces.king import King
